# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_pic', models.FileField(blank=True, default='images/blank_user.png', null=True, upload_to=users.models.get_upload_file_name)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('play_level', models.CharField(blank=True, max_length=50, null=True)),
                ('user_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
                ('user_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=250)),
                ('goal_target_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('goal_complete', models.BooleanField(default=False)),
                ('goal_complete_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('goal_notes', models.TextField(blank=True, null=True)),
                ('goal_created', models.DateTimeField(auto_now_add=True)),
                ('goal_updated', models.DateTimeField(auto_now=True)),
                ('goal_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_created_user', to=settings.AUTH_USER_MODEL)),
                ('goal_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_updated_user', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=250)),
                ('objective_complete', models.BooleanField(default=False)),
                ('objective_complete_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('objective_notes', models.TextField(blank=True, null=True)),
                ('objective_created', models.DateTimeField(auto_now_add=True)),
                ('objective_updated', models.DateTimeField(auto_now=True)),
                ('objective_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_created_user', to=settings.AUTH_USER_MODEL)),
                ('objective_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_updated_user', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPracticeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_item', models.CharField(max_length=50)),
                ('practice_time', models.CharField(blank=True, max_length=50, null=True)),
                ('practice_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('top_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('log_item_created', models.DateTimeField(auto_now_add=True)),
                ('log_item_updated', models.DateTimeField(auto_now=True)),
                ('log_item_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_created_user', to=settings.AUTH_USER_MODEL)),
                ('log_item_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_updated_user', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
