# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160424_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=250)),
                ('goal_target_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('goal_complete', models.BooleanField(default=False)),
                ('goal_complete_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('goal_notes', models.TextField(blank=True, null=True)),
                ('goal_created', models.DateTimeField(auto_now_add=True)),
                ('goal_updated', models.DateTimeField(auto_now=True)),
                ('goal_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_created_user', to=settings.AUTH_USER_MODEL)),
                ('goal_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_updated_user', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentObjectives',
            new_name='StudentObjective',
        ),
        migrations.RemoveField(
            model_name='studentgoals',
            name='goal_created_by',
        ),
        migrations.RemoveField(
            model_name='studentgoals',
            name='goal_updated_by',
        ),
        migrations.RemoveField(
            model_name='studentgoals',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentGoals',
        ),
    ]
