# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160426_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentobjective',
            name='objective_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentpracticelog',
            name='log_item_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_updated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
