# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160426_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpracticelog',
            name='log_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
