# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentpracticelog_log_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpracticelog',
            name='top_speed',
        ),
    ]
