# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160426_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpracticelog',
            name='practice_category',
            field=models.CharField(blank=True, choices=[('LEAD_TECHNIQUE', 'Lead Technique'), ('RHYTHM_TECHNIQUE', 'Rhythm Technique'), ('THEORY', 'Theory'), ('REPERTOIRE', 'Repertoire'), ('APPLIED_THEORY', 'Applied Theory')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentgoal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmaterial',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_material', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentobjective',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_objective', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentpracticelog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentwishlist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.FileField(blank=True, default='blank_user.png', null=True, upload_to=users.models.get_upload_file_name),
        ),
    ]
