# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160510_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpracticelog',
            old_name='log_item_created',
            new_name='practice_item_created',
        ),
        migrations.RenameField(
            model_name='studentpracticelog',
            old_name='log_item_created_by',
            new_name='practice_item_created_by',
        ),
        migrations.RenameField(
            model_name='studentpracticelog',
            old_name='log_item_updated',
            new_name='practice_item_updated',
        ),
        migrations.RenameField(
            model_name='studentpracticelog',
            old_name='log_item_updated_by',
            new_name='practice_item_updated_by',
        ),
        migrations.RenameField(
            model_name='studentpracticelog',
            old_name='log_notes',
            new_name='practice_notes',
        ),
    ]
