# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160510_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='play_level',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('BROWN', 'Brown'), ('BLACK', 'Black')], max_length=20, null=True),
        ),
    ]
