# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160514_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpracticelog',
            name='practice_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
