# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_studentmaterial_material_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmaterial',
            old_name='material',
            new_name='file',
        ),
    ]
