# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20160611_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_credit',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
