# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20160618_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
