# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20160624_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_credit',
            field=models.CharField(blank=True, default=0, max_length=4, null=True),
        ),
    ]
