# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 23:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20160908_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 8, 23, 31, 45, 922903, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_created_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
