# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20160908_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_created', models.DateTimeField(auto_now_add=True)),
                ('note_updated', models.DateTimeField(auto_now_add=True)),
                ('note_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_created_user', to=settings.AUTH_USER_MODEL)),
                ('note_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_updated_user', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='location_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
