# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20160911_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentobjective',
            name='objective_visible',
            field=models.BooleanField(default=False),
        ),
    ]
