# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20160911_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnote',
            name='note_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_updated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
