# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20160911_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaterial',
            name='student_group',
            field=models.ManyToManyField(null=True, related_name='group_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='note_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
