# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20160926_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaterial',
            name='material_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_added_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
