# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20160929_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_update',
            field=models.BooleanField(default=True),
        ),
    ]
