# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_studentemail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentemail',
            name='bcc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentemail',
            name='cc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentemail',
            name='from_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
