# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20161004_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentemail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('CRE', 'User Created'), ('ACT', 'User Active'), ('UPD', 'Account Updated'), ('PRACT', 'User Practice Reminder'), ('SCHED', 'Course Scheduled'), ('CNCL', 'Course Cancelled'), ('REMD', 'Course Scheduled Reminder')], max_length=8, null=True),
        ),
    ]
