# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-21 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_studentmaterialuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50)),
                ('label_created', models.DateTimeField(auto_now=True)),
                ('label_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentmaterial',
            name='material_label',
            field=models.ManyToManyField(blank=True, related_name='label_material', to='users.StudentLabel'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='note_label',
            field=models.ManyToManyField(blank=True, related_name='label_note', to='users.StudentLabel'),
        ),
    ]
