# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-06 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_studentfeedback_studentfeedbackmaterial_studentfeedbackreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='feedback_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentfeedbackmaterial',
            name='feedback_material_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentfeedbackreply',
            name='reply_feedback_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
