# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-06 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20170605_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedbackmaterial',
            name='student_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_feedback', to='users.StudentFeedback'),
        ),
    ]
