# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-06 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20170605_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
