# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-22 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20170605_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeedback',
            old_name='feedback_notes',
            new_name='feedback_note',
        ),
    ]
