# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_categroy',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_topic', to='forum.Category'),
            preserve_default=False,
        ),
    ]
