# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20160523_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_file', models.FileField(blank=True, null=True, upload_to=users.models.get_upload_file_name)),
                ('message_file_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_message', to='forum.Message')),
                ('message_file_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
