# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=100, null=True)),
                ('course_subtitle', models.CharField(blank=True, max_length=240, null=True)),
                ('course_length', models.CharField(blank=True, max_length=3, null=True)),
                ('course_days', models.CharField(blank=True, choices=[('ALL', 'All'), ('WEK', 'Week'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='ALL', max_length=3, null=True)),
                ('course_avail_start', models.CharField(blank=True, max_length=6, null=True)),
                ('course_avail_end', models.CharField(blank=True, max_length=6, null=True)),
                ('course_notes', models.TextField(blank=True, null=True)),
                ('course_created', models.DateTimeField(auto_now_add=True)),
                ('course_age_range', models.CharField(blank=True, max_length=10, null=True)),
                ('rank_white', models.BooleanField(default=True)),
                ('rank_red', models.BooleanField(default=True)),
                ('rank_yellow', models.BooleanField(default=True)),
                ('rank_green', models.BooleanField(default=True)),
                ('rank_blue', models.BooleanField(default=True)),
                ('rank_porple', models.BooleanField(default=True)),
                ('rank_brown', models.BooleanField(default=True)),
                ('rank_black', models.BooleanField(default=True)),
                ('practice_min', models.CharField(blank=True, default=0, max_length=4, null=True)),
                ('course_credit', models.CharField(blank=True, default=0, max_length=3, null=True)),
                ('max_student', models.CharField(blank=True, max_length=2, null=True)),
                ('course_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('schedule_start_time', models.CharField(blank=True, max_length=6, null=True)),
                ('schedule_end_time', models.CharField(blank=True, max_length=6, null=True)),
                ('schedule_notes', models.TextField(blank=True, null=True)),
                ('schedule_created', models.DateTimeField(auto_now_add=True)),
                ('schedule_updated', models.DateTimeField(auto_now_add=True)),
                ('schedule_canceled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Course')),
                ('schedule_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_created', to=settings.AUTH_USER_MODEL)),
                ('schedule_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_updated', to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, null=True, related_name='course_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
