# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160618_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='schedule_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
