# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20160618_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='schedule_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
