# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20160618_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_private',
            field=models.BooleanField(default=False),
        ),
    ]
