# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_course_course_private_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rank_porple',
            new_name='rank_purple',
        ),
    ]
