# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20160622_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_fri',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_mon',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_sat',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_sun',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_thu',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_tue',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_wed',
            new_name='wednesday',
        ),
    ]
