# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20160622_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_avail_end',
            new_name='course_end_time',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_avail_start',
            new_name='course_start_time',
        ),
    ]
