# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20160630_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_active',
            field=models.BooleanField(default=True),
        ),
    ]
