# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20160701_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_recurring',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_age_max',
            field=models.CharField(blank=True, default=99, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_age_min',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
    ]
