# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20160908_1846'),
        ('schedule', '0018_auto_20160702_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_course', to='users.Location'),
        ),
    ]
