# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0021_remove_course_course_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='schedule_recurring_user',
            field=models.ManyToManyField(blank=True, related_name='user_recurring', to=settings.AUTH_USER_MODEL),
        ),
    ]
