# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-15 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0022_courseschedule_schedule_recurring_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_created', models.DateTimeField(auto_now_add=True)),
                ('message_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_material', models.FileField(blank=True, null=True, upload_to=users.models.get_upload_file_name)),
                ('message_material_created', models.DateTimeField(auto_now_add=True)),
                ('message_material_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(blank=True, null=True)),
                ('reply_message_created', models.DateTimeField(auto_now_add=True)),
                ('reply_message_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messaging.Message')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedback', to='schedule.CourseSchedule')),
            ],
            bases=('messaging.message',),
        ),
        migrations.AddField(
            model_name='messagereply',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_message', to='messaging.Message'),
        ),
        migrations.AddField(
            model_name='messagereply',
            name='reply_message_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_message_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereply',
            name='reply_message_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_message_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagematerial',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_message', to='messaging.Message'),
        ),
        migrations.AddField(
            model_name='messagematerial',
            name='message_material_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_material_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagematerial',
            name='message_material_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_material_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='message_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='message_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='message_user',
            field=models.ManyToManyField(blank=True, related_name='student_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
