# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-20 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20171019_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroup',
            name='message_group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
