# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20171019_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='message_group_visible',
            field=models.BooleanField(default=True),
        ),
    ]
